_ETHOS_PACKAGES = [
    {
        'id': 'surveillance',
        'name': 'Surveillance Station',
        'icon': 'fa-video',
        'color': '#dc2626',
        'description': 'System monitoringu kamer IP — wykrywanie ruchu, nagrywanie ciągłe i zdarzeniowe, podgląd na żywo.',
        'app_id': 'surveillance',
        'deps_label': 'ffmpeg, ffprobe, python-onvif',
        'install_endpoint': '/api/surveillance/install',
        'uninstall_endpoint': '/api/surveillance/uninstall',
        'status_endpoint': '/api/surveillance/status',
    },
    {
        'id': 'ai-chat',
        'name': 'AI Chat',
        'icon': 'fa-robot',
        'color': '#8b5cf6',
        'description': 'Asystent AI z narzędziami deweloperskimi — czat z GPT, Claude, lokalnymi modelami LLM (GGUF). '
                       'Obsługuje OpenAI, Azure, własne endpointy oraz lokalne modele z Hugging Face.',
        'app_id': 'ai-chat',
        'deps_label': 'llama-cpp-python (lokalne modele)',
        'install_endpoint': '/api/aichat/install',
        'uninstall_endpoint': '/api/aichat/uninstall',
        'status_endpoint': '/api/aichat/status',
    },
    {
        'id': 'gallery',
        'name': 'Galeria',
        'icon': 'fa-images',
        'color': '#ec4899',
        'description': 'Galeria zdjęć i filmów z wybranych folderów — EXIF, miniatury, ulubione, hasła folderów.',
        'app_id': 'gallery',
        'deps_label': 'brak wymagań',
        'install_endpoint': '/api/gallery/install',
        'uninstall_endpoint': '/api/gallery/uninstall',
        'status_endpoint': '/api/gallery/pkg-status',
    },
    {
        'id': 'download-manager',
        'name': 'Menedżer pobierania',
        'icon': 'fa-cloud-download-alt',
        'color': '#10b981',
        'description': 'Pobieraj pliki z usługami premium (AllDebrid, Real-Debrid, Premiumize) — HTTP, torrent, magnet.',
        'app_id': 'download-manager',
        'deps_label': 'opcjonalnie: konto debrid',
        'install_endpoint': '/api/downloads/install',
        'uninstall_endpoint': '/api/downloads/uninstall',
        'status_endpoint': '/api/downloads/pkg-status',
    },
    {
        'id': 'printer',
        'name': 'Serwer druku',
        'icon': 'fa-print',
        'color': '#ef4444',
        'description': 'Drukowanie dokumentów przez CUPS — automatyczne wykrywanie drukarek, konwersja do PDF.',
        'app_id': 'printer',
        'deps_label': 'cups, libreoffice',
        'install_endpoint': '/api/printer/install',
        'uninstall_endpoint': '/api/printer/uninstall',
        'status_endpoint': '/api/printer/pkg-status',
    },
    {
        'id': 'docker-manager',
        'name': 'Docker',
        'icon': 'fa-cubes',
        'color': '#2496ed',
        'description': 'Zarządzanie kontenerami, projektami Docker Compose, obrazami i logami.',
        'app_id': 'docker-manager',
        'deps_label': 'docker, docker-compose',
        'install_endpoint': '/api/docker/install',
        'uninstall_endpoint': '/api/docker/uninstall',
        'status_endpoint': '/api/docker/pkg-status',
    },
    {
        'id': 'vm-manager',
        'name': 'VM Manager',
        'icon': 'fa-desktop',
        'color': '#8b5cf6',
        'description': 'Twórz i zarządzaj wirtualnymi maszynami (QEMU/KVM) — uruchamiaj ISO, IMG, QCOW2. '
                       'Snapshoty, zmiana rozmiaru dysku, VNC dostęp.',
        'app_id': 'vm-manager',
        'deps_label': 'qemu-system-x86, qemu-utils, ovmf',
        'install_endpoint': '/api/vm/install',
        'uninstall_endpoint': '/api/vm/uninstall',
        'status_endpoint': '/api/vm/pkg-status',
    },
    {
        'id': 'doc-editor',
        'name': 'Edytor dokumentów',
        'icon': 'fa-file-word',
        'color': '#2563eb',
        'description': 'Twórz i edytuj dokumenty Word, eksportuj do PDF — wymaga LibreOffice.',
        'app_id': 'doc-editor',
        'deps_label': 'libreoffice, mammoth',
        'install_endpoint': '/api/editor/install',
        'uninstall_endpoint': '/api/editor/uninstall',
        'status_endpoint': '/api/editor/pkg-status',
    },
    {
        'id': 'code-editor',
        'name': 'Edytor kodu',
        'icon': 'fa-code',
        'color': '#22d3ee',
        'description': 'Prosty edytor kodu z numerami linii, podświetlaniem składni i formatowaniem.',
        'app_id': 'code-editor',
        'deps_label': 'brak wymagań',
        'install_endpoint': '/api/code-editor/install',
        'uninstall_endpoint': '/api/code-editor/uninstall',
        'status_endpoint': '/api/code-editor/pkg-status',
    },
    {
        'id': 'duplicates',
        'name': 'Duplikaty zdjęć',
        'icon': 'fa-clone',
        'color': '#a78bfa',
        'description': 'Znajdź identyczne i podobne zdjęcia na dysku — hash perceptualny.',
        'app_id': 'duplicates',
        'deps_label': 'brak wymagań',
        'install_endpoint': '/api/files/duplicates/install',
        'uninstall_endpoint': '/api/files/duplicates/uninstall',
        'status_endpoint': '/api/files/duplicates/pkg-status',
    },
    {
        'id': 'usb-flasher',
        'name': 'Kreator USB',
        'icon': 'fa-usb',
        'color': '#a855f7',
        'description': 'Flashuj obrazy ISO/IMG na dyski USB z podglądem postępu.',
        'app_id': 'usb-flasher',
        'deps_label': 'dd',
        'install_endpoint': '/api/flasher/install',
        'uninstall_endpoint': '/api/flasher/uninstall',
        'status_endpoint': '/api/flasher/pkg-status',
    },
    {
        'id': 'builder',
        'name': 'Builder',
        'icon': 'fa-hammer',
        'color': '#f97316',
        'description': 'Buduj release i obrazy systemu EthOS ze strony web.',
        'app_id': 'builder',
        'deps_label': 'squashfs-tools, genisoimage',
        'install_endpoint': '/api/builder/install',
        'uninstall_endpoint': '/api/builder/uninstall',
        'status_endpoint': '/api/builder/pkg-status',
    },
    {
        'id': 'disk-repair',
        'name': 'Naprawa dysków',
        'icon': 'fa-wrench',
        'color': '#ef4444',
        'description': 'Diagnostyka SMART, sprawdzanie i naprawa systemów plików (fsck, e2fsck, ntfsfix).',
        'app_id': 'disk-repair',
        'deps_label': 'smartmontools, e2fsprogs',
        'install_endpoint': '/api/diskrepair/install',
        'uninstall_endpoint': '/api/diskrepair/uninstall',
        'status_endpoint': '/api/diskrepair/pkg-status',
    },
    {
        'id': 'remote-log',
        'name': 'Zdalne logi',
        'icon': 'fa-satellite-dish',
        'color': '#0891b2',
        'description': 'Wysyłanie logów diagnostycznych na serwer centralny i odbiór logów z urządzeń.',
        'app_id': 'remote-log',
        'deps_label': 'brak wymagań',
        'install_endpoint': '/api/remote-log/install',
        'uninstall_endpoint': '/api/remote-log/uninstall',
        'status_endpoint': '/api/remote-log/pkg-status',
    },
    {
        'id': 'sharing-samba',
        'name': 'Samba (SMB)',
        'icon': 'fa-windows',
        'color': '#6366f1',
        'description': 'Udziały sieciowe Samba — foldery współdzielone widoczne w sieci lokalnej (Windows, Mac, Linux).',
        'app_id': 'sharing',
        'deps_label': 'samba',
        'install_endpoint': '/api/storage/samba/pkg-install',
        'uninstall_endpoint': '/api/storage/samba/pkg-uninstall',
        'status_endpoint': '/api/storage/samba/pkg-status',
    },
    {
        'id': 'sharing-nfs',
        'name': 'NFS',
        'icon': 'fa-network-wired',
        'color': '#6366f1',
        'description': 'Eksporty NFS — szybki udział plików dla systemów Linux/Unix.',
        'app_id': 'sharing',
        'deps_label': 'nfs-kernel-server',
        'install_endpoint': '/api/storage/nfs/pkg-install',
        'uninstall_endpoint': '/api/storage/nfs/pkg-uninstall',
        'status_endpoint': '/api/storage/nfs/pkg-status',
    },
    {
        'id': 'sharing-dlna',
        'name': 'DLNA (MiniDLNA)',
        'icon': 'fa-photo-video',
        'color': '#6366f1',
        'description': 'Serwer multimediów DLNA — strumieniowanie muzyki, filmów i zdjęć na telewizory i odtwarzacze.',
        'app_id': 'sharing',
        'deps_label': 'minidlna',
        'install_endpoint': '/api/storage/dlna/pkg-install',
        'uninstall_endpoint': '/api/storage/dlna/pkg-uninstall',
        'status_endpoint': '/api/storage/dlna/pkg-status',
    },
    {
        'id': 'sharing-webdav',
        'name': 'WebDAV',
        'icon': 'fa-globe',
        'color': '#6366f1',
        'description': 'Serwer WebDAV — dostęp do plików przez HTTP z uwierzytelnianiem.',
        'app_id': 'sharing',
        'deps_label': 'lighttpd',
        'install_endpoint': '/api/storage/webdav/pkg-install',
        'uninstall_endpoint': '/api/storage/webdav/pkg-uninstall',
        'status_endpoint': '/api/storage/webdav/pkg-status',
    },
    {
        'id': 'sharing-sftp',
        'name': 'SFTP',
        'icon': 'fa-lock',
        'color': '#6366f1',
        'description': 'Bezpieczny transfer plików przez SSH — szyfrowane połączenie.',
        'app_id': 'sharing',
        'deps_label': 'openssh-server',
        'install_endpoint': '/api/storage/sftp/pkg-install',
        'uninstall_endpoint': '/api/storage/sftp/pkg-uninstall',
        'status_endpoint': '/api/storage/sftp/pkg-status',
    },
    {
        'id': 'sharing-ftp',
        'name': 'FTP',
        'icon': 'fa-upload',
        'color': '#6366f1',
        'description': 'Serwer FTP (vsftpd) — klasyczny protokół transferu plików.',
        'app_id': 'sharing',
        'deps_label': 'vsftpd',
        'install_endpoint': '/api/storage/ftp/pkg-install',
        'uninstall_endpoint': '/api/storage/ftp/pkg-uninstall',
        'status_endpoint': '/api/storage/ftp/pkg-status',
    },
    {
        'id': 'domains-manager',
        'name': 'Domeny i SSL',
        'icon': 'fa-globe',
        'color': '#059669',
        'description': 'Zarządzanie domenami, certyfikatami SSL, reverse proxy i Dynamic DNS '
                       '— DuckDNS, Cloudflare, No-IP, Let\u2019s Encrypt.',
        'app_id': 'domains-manager',
        'deps_label': 'certbot (opcjonalnie)',
        'install_endpoint': '/api/ddns/install',
        'uninstall_endpoint': '/api/ddns/uninstall',
        'status_endpoint': '/api/ddns/pkg-status',
    },
    {
        'id': 'websites',
        'name': 'Strony WWW',
        'icon': 'fa-globe-americas',
        'color': '#14b8a6',
        'description': 'Kreator stron internetowych z prostym CMS — szablony, edytor wizualny, hosting.',
        'app_id': 'websites',
        'deps_label': 'brak wymagań',
        'install_endpoint': '/api/websites/install',
        'uninstall_endpoint': '/api/websites/uninstall',
        'status_endpoint': '/api/websites/pkg-status',
    },
]
