_ETHOS_PACKAGES = [
    {
        'id': 'surveillance',
        'name': 'Surveillance Station',
        'icon': 'fa-video',
        'color': '#dc2626',
        'description': 'IP camera monitoring system — motion detection, continuous and event recording, live preview.',
        'app_id': 'surveillance',
        'deps_label': 'ffmpeg, ffprobe, python-onvif',
        'install_endpoint': '/api/surveillance/install',
        'uninstall_endpoint': '/api/surveillance/uninstall',
        'status_endpoint': '/api/surveillance/status',
    },
    {
        'id': 'ai-chat',
        'name': 'AI Chat',
        'icon': 'fa-robot',
        'color': '#8b5cf6',
        'description': 'AI assistant with developer tools — chat with GPT, Claude, local LLM models (GGUF). '
                       'Supports OpenAI, Azure, custom endpoints, and local models from Hugging Face.',
        'app_id': 'ai-chat',
        'deps_label': 'llama-cpp-python (local models)',
        'install_endpoint': '/api/aichat/install',
        'uninstall_endpoint': '/api/aichat/uninstall',
        'status_endpoint': '/api/aichat/status',
    },
    {
        'id': 'gallery',
        'name': 'Gallery',
        'icon': 'fa-images',
        'color': '#ec4899',
        'description': 'Photo and video gallery from selected folders — EXIF, thumbnails, favorites, folder passwords.',
        'app_id': 'gallery',
        'deps_label': 'no requirements',
        'install_endpoint': '/api/gallery/install',
        'uninstall_endpoint': '/api/gallery/uninstall',
        'status_endpoint': '/api/gallery/pkg-status',
    },
    {
        'id': 'download-manager',
        'name': 'Download Manager',
        'icon': 'fa-cloud-download-alt',
        'color': '#10b981',
        'description': 'Download files with premium services (AllDebrid, Real-Debrid, Premiumize) — HTTP, torrent, magnet.',
        'app_id': 'download-manager',
        'deps_label': 'optional: debrid account',
        'install_endpoint': '/api/downloads/install',
        'uninstall_endpoint': '/api/downloads/uninstall',
        'status_endpoint': '/api/downloads/pkg-status',
    },
    {
        'id': 'printer',
        'name': 'Print Server',
        'icon': 'fa-print',
        'color': '#ef4444',
        'description': 'Print documents via CUPS — automatic printer detection, PDF conversion.',
        'app_id': 'printer',
        'deps_label': 'cups, libreoffice',
        'install_endpoint': '/api/printer/install',
        'uninstall_endpoint': '/api/printer/uninstall',
        'status_endpoint': '/api/printer/pkg-status',
    },
    {
        'id': 'docker-manager',
        'name': 'Docker',
        'icon': 'fa-cubes',
        'color': '#2496ed',
        'description': 'Manage containers, Docker Compose projects, images, and logs.',
        'app_id': 'docker-manager',
        'deps_label': 'docker, docker-compose',
        'install_endpoint': '/api/docker/install',
        'uninstall_endpoint': '/api/docker/uninstall',
        'status_endpoint': '/api/docker/pkg-status',
    },
    {
        'id': 'vm-manager',
        'name': 'VM Manager',
        'icon': 'fa-desktop',
        'color': '#8b5cf6',
        'description': 'Create and manage virtual machines (QEMU/KVM) — run ISO, IMG, QCOW2. '
                       'Snapshots, disk resizing, VNC access.',
        'app_id': 'vm-manager',
        'deps_label': 'qemu-system-x86, qemu-utils, ovmf',
        'install_endpoint': '/api/vm/install',
        'uninstall_endpoint': '/api/vm/uninstall',
        'status_endpoint': '/api/vm/pkg-status',
    },
    {
        'id': 'doc-editor',
        'name': 'Document Editor',
        'icon': 'fa-file-word',
        'color': '#2563eb',
        'description': 'Create and edit Word documents, export to PDF — requires LibreOffice.',
        'app_id': 'doc-editor',
        'deps_label': 'libreoffice, mammoth',
        'install_endpoint': '/api/editor/install',
        'uninstall_endpoint': '/api/editor/uninstall',
        'status_endpoint': '/api/editor/pkg-status',
    },
    {
        'id': 'code-editor',
        'name': 'Code Editor',
        'icon': 'fa-code',
        'color': '#22d3ee',
        'description': 'Simple code editor with line numbers, syntax highlighting, and formatting.',
        'app_id': 'code-editor',
        'deps_label': 'no requirements',
        'install_endpoint': '/api/code-editor/install',
        'uninstall_endpoint': '/api/code-editor/uninstall',
        'status_endpoint': '/api/code-editor/pkg-status',
    },
    {
        'id': 'duplicates',
        'name': 'Photo Duplicates',
        'icon': 'fa-clone',
        'color': '#a78bfa',
        'description': 'Find identical and similar photos on disk — perceptual hashing.',
        'app_id': 'duplicates',
        'deps_label': 'no requirements',
        'install_endpoint': '/api/files/duplicates/install',
        'uninstall_endpoint': '/api/files/duplicates/uninstall',
        'status_endpoint': '/api/files/duplicates/pkg-status',
    },
    {
        'id': 'usb-flasher',
        'name': 'USB Flasher',
        'icon': 'fa-usb',
        'color': '#a855f7',
        'description': 'Flash ISO/IMG images to USB drives with progress preview.',
        'app_id': 'usb-flasher',
        'deps_label': 'dd',
        'install_endpoint': '/api/flasher/install',
        'uninstall_endpoint': '/api/flasher/uninstall',
        'status_endpoint': '/api/flasher/pkg-status',
    },
    {
        'id': 'builder',
        'name': 'Builder',
        'icon': 'fa-hammer',
        'color': '#f97316',
        'description': 'Build releases and EthOS system images from the web interface.',
        'app_id': 'builder',
        'deps_label': 'squashfs-tools, genisoimage',
        'install_endpoint': '/api/builder/install',
        'uninstall_endpoint': '/api/builder/uninstall',
        'status_endpoint': '/api/builder/pkg-status',
    },
    {
        'id': 'disk-repair',
        'name': 'Disk Repair',
        'icon': 'fa-wrench',
        'color': '#ef4444',
        'description': 'SMART diagnostics, filesystem checking and repair (fsck, e2fsck, ntfsfix).',
        'app_id': 'disk-repair',
        'deps_label': 'smartmontools, e2fsprogs',
        'install_endpoint': '/api/diskrepair/install',
        'uninstall_endpoint': '/api/diskrepair/uninstall',
        'status_endpoint': '/api/diskrepair/pkg-status',
    },
    {
        'id': 'remote-log',
        'name': 'Remote Logs',
        'icon': 'fa-satellite-dish',
        'color': '#0891b2',
        'description': 'Send diagnostic logs to central server and receive logs from devices.',
        'app_id': 'remote-log',
        'deps_label': 'no requirements',
        'install_endpoint': '/api/remote-log/install',
        'uninstall_endpoint': '/api/remote-log/uninstall',
        'status_endpoint': '/api/remote-log/pkg-status',
    },
    {
        'id': 'sharing-samba',
        'name': 'Samba (SMB)',
        'icon': 'fa-windows',
        'color': '#6366f1',
        'description': 'Samba network shares — shared folders visible on local network (Windows, Mac, Linux).',
        'app_id': 'sharing',
        'deps_label': 'samba',
        'install_endpoint': '/api/storage/samba/pkg-install',
        'uninstall_endpoint': '/api/storage/samba/pkg-uninstall',
        'status_endpoint': '/api/storage/samba/pkg-status',
    },
    {
        'id': 'sharing-nfs',
        'name': 'NFS',
        'icon': 'fa-network-wired',
        'color': '#6366f1',
        'description': 'NFS exports — fast file sharing for Linux/Unix systems.',
        'app_id': 'sharing',
        'deps_label': 'nfs-kernel-server',
        'install_endpoint': '/api/storage/nfs/pkg-install',
        'uninstall_endpoint': '/api/storage/nfs/pkg-uninstall',
        'status_endpoint': '/api/storage/nfs/pkg-status',
    },
    {
        'id': 'sharing-dlna',
        'name': 'DLNA (MiniDLNA)',
        'icon': 'fa-photo-video',
        'color': '#6366f1',
        'description': 'DLNA media server — stream music, movies, and photos to TVs and players.',
        'app_id': 'sharing',
        'deps_label': 'minidlna',
        'install_endpoint': '/api/storage/dlna/pkg-install',
        'uninstall_endpoint': '/api/storage/dlna/pkg-uninstall',
        'status_endpoint': '/api/storage/dlna/pkg-status',
    },
    {
        'id': 'sharing-webdav',
        'name': 'WebDAV',
        'icon': 'fa-globe',
        'color': '#6366f1',
        'description': 'WebDAV server — file access over HTTP with authentication.',
        'app_id': 'sharing',
        'deps_label': 'lighttpd',
        'install_endpoint': '/api/storage/webdav/pkg-install',
        'uninstall_endpoint': '/api/storage/webdav/pkg-uninstall',
        'status_endpoint': '/api/storage/webdav/pkg-status',
    },
    {
        'id': 'sharing-sftp',
        'name': 'SFTP',
        'icon': 'fa-lock',
        'color': '#6366f1',
        'description': 'Secure file transfer over SSH — encrypted connection.',
        'app_id': 'sharing',
        'deps_label': 'openssh-server',
        'install_endpoint': '/api/storage/sftp/pkg-install',
        'uninstall_endpoint': '/api/storage/sftp/pkg-uninstall',
        'status_endpoint': '/api/storage/sftp/pkg-status',
    },
    {
        'id': 'sharing-ftp',
        'name': 'FTP',
        'icon': 'fa-upload',
        'color': '#6366f1',
        'description': 'FTP server (vsftpd) — classic file transfer protocol.',
        'app_id': 'sharing',
        'deps_label': 'vsftpd',
        'install_endpoint': '/api/storage/ftp/pkg-install',
        'uninstall_endpoint': '/api/storage/ftp/pkg-uninstall',
        'status_endpoint': '/api/storage/ftp/pkg-status',
    },
    {
        'id': 'domains-manager',
        'name': 'Domains & SSL',
        'icon': 'fa-globe',
        'color': '#059669',
        'description': 'Domain management, SSL certificates, reverse proxy, and Dynamic DNS '
                       '— DuckDNS, Cloudflare, No-IP, Let\u2019s Encrypt.',
        'app_id': 'domains-manager',
        'deps_label': 'certbot (optional)',
        'install_endpoint': '/api/ddns/install',
        'uninstall_endpoint': '/api/ddns/uninstall',
        'status_endpoint': '/api/ddns/pkg-status',
    },
    {
        'id': 'websites',
        'name': 'Websites',
        'icon': 'fa-globe-americas',
        'color': '#14b8a6',
        'description': 'Website builder with simple CMS — templates, visual editor, hosting.',
        'app_id': 'websites',
        'deps_label': 'no requirements',
        'install_endpoint': '/api/websites/install',
        'uninstall_endpoint': '/api/websites/uninstall',
        'status_endpoint': '/api/websites/pkg-status',
    },
]
